unit TestColorsFrm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, ColorsFrm, SysUtils, Windows, StdCtrls, BaseForm, Messages, Variants, 
  Controls, Classes, Dialogs, AppOptions, Forms, TntStdCtrls, ExtCtrls, Graphics;
type
  // Test methods for class TfrmColors
  
  TestTfrmColors = class(TTestCase)
  strict private
    FfrmColors: TfrmColors;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestEdit;
  end;

implementation

procedure TestTfrmColors.SetUp;
begin
  FfrmColors := TfrmColors.Create(nil);
end;

procedure TestTfrmColors.TearDown;
begin
  FfrmColors.Free;
  FfrmColors := nil;
end;

procedure TestTfrmColors.TestEdit;
var
  ReturnValue: Boolean;
  Options: TAppOptions;
begin
  // TODO: Setup method call parameters
  ReturnValue := FfrmColors.Edit(Options);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmColors.Suite);
end.

